FROM nvidia/cuda:11.6.0-devel-ubuntu20.04

LABEL maintainer="Ömercan Yazici" \
      description="Anydsl Meta package for AVX2 and with GPU CUDA support" \
      version="0.1.0"

ENV DEBIAN_FRONTEND noninteractive
ENV CUDAToolkit_LIBRARY_ROOT /usr/local/cuda

RUN mkdir -p /anydsl
COPY . /anydsl
WORKDIR /anydsl

RUN apt-get update && /anydsl/docker/setup_newest_cmake.sh && apt-get install -y build-essential g++ git subversion zlib1g-dev cmake ninja-build && rm -rf /var/lib/apt/lists/* 
RUN cp docker/config-jit.sh.template config.sh && chmod +x setup.sh && chmod +x docker/cleanup.sh
RUN ./setup.sh && ./docker/cleanup.sh
