FROM gcc:11

LABEL maintainer="Ömercan Yazici" \
      description="Anydsl Meta package for AVX2 without GPU support" \
      version="0.1.0"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y cmake ninja-build && rm -rf /var/lib/apt/lists/* 

RUN mkdir -p /anydsl
COPY . /anydsl
WORKDIR /anydsl
RUN cp docker/config-avx2-jit.sh.template config.sh && chmod +x setup.sh && chmod +x docker/cleanup.sh
RUN ./setup.sh && ./docker/cleanup.sh

